name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r rag-chat/requirements.txt
      - name: Lint import
        run: |
          python -c "import fastapi, langchain"
      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: rag-chat
          push: false

